name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip ant python3-pip python3-setuptools \
          libncurses5 libstdc++6 zlib1g-dev libffi-dev libssl-dev python3-dev \
          build-essential mesa-common-dev libglu1-mesa-dev freeglut3-dev libgles2-mesa-dev \
          libmtdev-dev xclip xsel libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
          libswscale-dev libavformat-dev libavcodec-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: pip install --user --upgrade buildozer cython==0.29.33

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          export APP_ALLOW_ROOT=1
          buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BurpMobile-App
          path: bin/*.apk
          
