name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip ant python3-pip python3-setuptools \
          libncurses5 libstdc++6 zlib1g-dev libffi-dev libssl-dev python3-dev \
          build-essential libunwind-dev libgstreamer1.0-dev gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
          libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer and Cython
        run: |
          pip install --user --upgrade buildozer cython==0.29.33

      - name: Install Android SDK tools (Fix Aidl error)
        run: |
          # هذه الخطوة تضمن وجود الـ AIDL والـ SDK في مساره الصحيح
          sudo apt install -y openjdk-17-jdk
          pip install --user sh

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          export APP_ALLOW_ROOT=1
          # استخدام yes لإعطاء موافقة تلقائية على كل شروط الـ SDK
          yes | buildozer android debug
        
            - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BurpMobile-App
          path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/burpmobile__arm64-v8a/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
          
