name: Build Kivy App to APK

on:
  push:
    branches:
      - main # This triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3' # Or a specific version like '3.7'

      - name: Build with Buildozer Action
        uses: digreatbrian/buildozer-action@v1
        with:
          # Modify these values to match your buildozer.spec file or specific requirements
          buildozer-cmd: buildozer android debug
          # Optional: specify a working directory if main.py is not in the root
          # work-dir: ./path/to/your/app
          # Optional: specify requirements if they are not in buildozer.spec
          # requirements: python3,kivy,buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk # The resulting APK file will be in the 'bin' directory
          
